# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60927be80a177b3793c63b42c3f08d6cef1223ac315e01f78b8052d99835de122e57993016d508224ce2d9c5954ed272fbbcafb3be7a093050370278f335b874
  facebook_app_id: 1764074837208338
  facebook_app_secret: 4fa702ce3d52640be3959df87511a17e

test:
  secret_key_base: 6edc072e7d81ca92efa8c54c999ac2d7bd160f7173d63760d348cc931c22994e8b308fd7041602b84e478964336112d8184bc83760e95f040b5b7f57a35aa57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
